name: kaya monitor

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9eef2154d4e27a

      - name: Setup Python
        uses: actions/setup-python@f3829084cb8415bcba17f265f7258967ba192192
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run monitor
        run: python monitor.py
